// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: proto/coefficient.proto

package live

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SportRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Sport                 string                 `protobuf:"bytes,1,opt,name=sport,proto3" json:"sport,omitempty"`
	UpdateIntervalSeconds uint32                 `protobuf:"varint,2,opt,name=update_interval_seconds,json=updateIntervalSeconds,proto3" json:"update_interval_seconds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SportRequest) Reset() {
	*x = SportRequest{}
	mi := &file_proto_coefficient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SportRequest) ProtoMessage() {}

func (x *SportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coefficient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SportRequest.ProtoReflect.Descriptor instead.
func (*SportRequest) Descriptor() ([]byte, []int) {
	return file_proto_coefficient_proto_rawDescGZIP(), []int{0}
}

func (x *SportRequest) GetSport() string {
	if x != nil {
		return x.Sport
	}
	return ""
}

func (x *SportRequest) GetUpdateIntervalSeconds() uint32 {
	if x != nil {
		return x.UpdateIntervalSeconds
	}
	return 0
}

type SportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Sport         string                 `protobuf:"bytes,3,opt,name=sport,proto3" json:"sport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SportResponse) Reset() {
	*x = SportResponse{}
	mi := &file_proto_coefficient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SportResponse) ProtoMessage() {}

func (x *SportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coefficient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SportResponse.ProtoReflect.Descriptor instead.
func (*SportResponse) Descriptor() ([]byte, []int) {
	return file_proto_coefficient_proto_rawDescGZIP(), []int{1}
}

func (x *SportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SportResponse) GetSport() string {
	if x != nil {
		return x.Sport
	}
	return ""
}

var File_proto_coefficient_proto protoreflect.FileDescriptor

const file_proto_coefficient_proto_rawDesc = "" +
	"\n" +
	"\x17proto/coefficient.proto\x12\x04live\"\\\n" +
	"\fSportRequest\x12\x14\n" +
	"\x05sport\x18\x01 \x01(\tR\x05sport\x126\n" +
	"\x17update_interval_seconds\x18\x02 \x01(\rR\x15updateIntervalSeconds\"Y\n" +
	"\rSportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05sport\x18\x03 \x01(\tR\x05sport2R\n" +
	"\x12CoefficientService\x12<\n" +
	"\x11StartSportUpdates\x12\x12.live.SportRequest\x1a\x13.live.SportResponseB)Z'github.com/VaheMuradyan/Live/proto;liveb\x06proto3"

var (
	file_proto_coefficient_proto_rawDescOnce sync.Once
	file_proto_coefficient_proto_rawDescData []byte
)

func file_proto_coefficient_proto_rawDescGZIP() []byte {
	file_proto_coefficient_proto_rawDescOnce.Do(func() {
		file_proto_coefficient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coefficient_proto_rawDesc), len(file_proto_coefficient_proto_rawDesc)))
	})
	return file_proto_coefficient_proto_rawDescData
}

var file_proto_coefficient_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_coefficient_proto_goTypes = []any{
	(*SportRequest)(nil),  // 0: live.SportRequest
	(*SportResponse)(nil), // 1: live.SportResponse
}
var file_proto_coefficient_proto_depIdxs = []int32{
	0, // 0: live.CoefficientService.StartSportUpdates:input_type -> live.SportRequest
	1, // 1: live.CoefficientService.StartSportUpdates:output_type -> live.SportResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_coefficient_proto_init() }
func file_proto_coefficient_proto_init() {
	if File_proto_coefficient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coefficient_proto_rawDesc), len(file_proto_coefficient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coefficient_proto_goTypes,
		DependencyIndexes: file_proto_coefficient_proto_depIdxs,
		MessageInfos:      file_proto_coefficient_proto_msgTypes,
	}.Build()
	File_proto_coefficient_proto = out.File
	file_proto_coefficient_proto_goTypes = nil
	file_proto_coefficient_proto_depIdxs = nil
}
