// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: proto/coefficient.proto

package live

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoefficientService_StartSportUpdates_FullMethodName = "/live.CoefficientService/StartSportUpdates"
	CoefficientService_StartEvents_FullMethodName       = "/live.CoefficientService/StartEvents"
)

// CoefficientServiceClient is the client API for CoefficientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoefficientServiceClient interface {
	StartSportUpdates(ctx context.Context, in *SportRequest, opts ...grpc.CallOption) (*SportResponse, error)
	StartEvents(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error)
}

type coefficientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoefficientServiceClient(cc grpc.ClientConnInterface) CoefficientServiceClient {
	return &coefficientServiceClient{cc}
}

func (c *coefficientServiceClient) StartSportUpdates(ctx context.Context, in *SportRequest, opts ...grpc.CallOption) (*SportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SportResponse)
	err := c.cc.Invoke(ctx, CoefficientService_StartSportUpdates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coefficientServiceClient) StartEvents(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, CoefficientService_StartEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoefficientServiceServer is the server API for CoefficientService service.
// All implementations must embed UnimplementedCoefficientServiceServer
// for forward compatibility.
type CoefficientServiceServer interface {
	StartSportUpdates(context.Context, *SportRequest) (*SportResponse, error)
	StartEvents(context.Context, *EventRequest) (*EventResponse, error)
	mustEmbedUnimplementedCoefficientServiceServer()
}

// UnimplementedCoefficientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoefficientServiceServer struct{}

func (UnimplementedCoefficientServiceServer) StartSportUpdates(context.Context, *SportRequest) (*SportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSportUpdates not implemented")
}
func (UnimplementedCoefficientServiceServer) StartEvents(context.Context, *EventRequest) (*EventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartEvents not implemented")
}
func (UnimplementedCoefficientServiceServer) mustEmbedUnimplementedCoefficientServiceServer() {}
func (UnimplementedCoefficientServiceServer) testEmbeddedByValue()                            {}

// UnsafeCoefficientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoefficientServiceServer will
// result in compilation errors.
type UnsafeCoefficientServiceServer interface {
	mustEmbedUnimplementedCoefficientServiceServer()
}

func RegisterCoefficientServiceServer(s grpc.ServiceRegistrar, srv CoefficientServiceServer) {
	// If the following call pancis, it indicates UnimplementedCoefficientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoefficientService_ServiceDesc, srv)
}

func _CoefficientService_StartSportUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoefficientServiceServer).StartSportUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoefficientService_StartSportUpdates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoefficientServiceServer).StartSportUpdates(ctx, req.(*SportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoefficientService_StartEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoefficientServiceServer).StartEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoefficientService_StartEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoefficientServiceServer).StartEvents(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoefficientService_ServiceDesc is the grpc.ServiceDesc for CoefficientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoefficientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "live.CoefficientService",
	HandlerType: (*CoefficientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSportUpdates",
			Handler:    _CoefficientService_StartSportUpdates_Handler,
		},
		{
			MethodName: "StartEvents",
			Handler:    _CoefficientService_StartEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/coefficient.proto",
}
